/***************** Get Pokemon list ***************************/
export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_POKEMON_LIST_SUCCESS = "GET_POKEMON_LIST_SUCCESS";
export const GET_POKEMON_LIST_FAILURE = "GET_POKEMON_LIST_FAILURE";
export const TOGGLE_POKEMON_TEAM_MEMBER = "TOGGLE_POKEMON_TEAM_MEMBER";
export const REMOVE_POKEMON_TEAM_MEMBER = "REMOVE_POKEMON_TEAM_MEMBER";
export const CHANGE_POKEMON_TEAM_ORDER = "CHANGE_POKEMON_TEAM_ORDER";
